# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88bfc2472c18add2b629e639b2470085b419ba3b4c1fcb5481829cc31cc1a4790f6f04a1b8f4c00bb25e344579bf0efb7490b118aa9b4e4c34344cba42351233

test:
  secret_key_base: 380fdad15e4d4a437a0c7988c675af5f6656df4a6e2a18dd06da5aa13605cb25a822dbe782c6d8f4338737bcaa161c180532ad3dc57d7e81e0eb7cb134b51159

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
